#spring:
#   #JPA
#   jpa: 
#      show-sql: false
#      properties: 
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          show_sql: false      
#          type: debug   
#   datasource:
#      url: jdbc:postgresql://postgresql:5432/inventorydb
#      username: inventory
#      test-on-borrow: true
#      validation-query: SELECT 1       
#   #ThymeLeaf       
#   thymeleaf.cache: false
#   

server.port: 9091

spring:
   thymeleaf.cache: false
 